name: Deploy to AWS EC2 Production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug - List files in repository
        run: ls -la

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ehrprod:latest .

      - name: Tag and Push Image to DockerHub
        run: |
          docker tag ehrprod:latest ${{ secrets.DOCKER_USERNAME }}/ehrprod:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/ehrprod:latest

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USERNAME }}
            key: ${{ secrets.KEY }}
            script: |
              sudo docker pull ${{ secrets.DOCKER_USERNAME }}/ehrprod:latest
              sudo docker stop ehrprod || true
              sudo docker rm ehrprod || true
              sudo docker system prune -af
              sudo docker run -d \
              --name ehrprod \
              -e PORT=4000 \
              -e MONGO_URI="${{ secrets.PROD_MONGO_URI }}" \
              -e SMTP_HOST="${{ secrets.PROD_SMTP_HOST }}" \
              -e SMTP_USER="${{ secrets.PROD_SMTP_USER }}" \
              -e SMTP_PASS="${{ secrets.PROD_SMTP_PASS }}" \
              -e SMTP_PORT="${{ secrets.PROD_SMTP_PORT }}" \
              -e JWT_SECRET="${{ secrets.PROD_JWT_SECRET }}" \
              -p 4000:4000 \
              ${{ secrets.DOCKER_USERNAME }}/ehrprod:latest
